'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1318
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System.Data



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IMyCalls")> _
Public Interface IMyCalls

	' CODEGEN: Parameter 'MyEchoResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
	<System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMyCalls/MyEcho", ReplyAction:="http://tempuri.org/IMyCalls/MyEchoResponse"), System.ServiceModel.XmlSerializerFormatAttribute()> _
	Function MyEcho(ByVal request As MyEchoRequest) As MyEchoResponse

	' CODEGEN: Parameter 'OpenRowsetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
	<System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMyCalls/OpenRowset", ReplyAction:="http://tempuri.org/IMyCalls/OpenRowsetResponse"), System.ServiceModel.XmlSerializerFormatAttribute()> _
	Function OpenRowset(ByVal request As OpenRowsetRequest) As OpenRowsetResponse
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.MessageContractAttribute(WrapperName:="MyEcho", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
Public Partial Class MyEchoRequest

	<System.ServiceModel.MessageBodyMemberAttribute(Namespace:="http://tempuri.org/", Order:=0), System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
	Public strInput As String

	Public Sub New()
	End Sub

	Public Sub New(ByVal strInput As String)
		Me.strInput = strInput
	End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.MessageContractAttribute(WrapperName:="MyEchoResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
Public Partial Class MyEchoResponse

	<System.ServiceModel.MessageBodyMemberAttribute(Namespace:="http://tempuri.org/", Order:=0), System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
	Public MyEchoResult As String

	Public Sub New()
	End Sub

	Public Sub New(ByVal MyEchoResult As String)
		Me.MyEchoResult = MyEchoResult
	End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.MessageContractAttribute(WrapperName:="OpenRowset", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
Public Partial Class OpenRowsetRequest

	<System.ServiceModel.MessageBodyMemberAttribute(Namespace:="http://tempuri.org/", Order:=0), System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
	Public strSQL As String

	Public Sub New()
	End Sub

	Public Sub New(ByVal strSQL As String)
		Me.strSQL = strSQL
	End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.MessageContractAttribute(WrapperName:="OpenRowsetResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=True)> _
Public Partial Class OpenRowsetResponse

    <System.ServiceModel.MessageBodyMemberAttribute(Namespace:="http://tempuri.org/", Order:=0), System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    Public OpenRowsetResult As System.Data.DataTable

    Public Sub New()
    End Sub

    Public Sub New(ByVal OpenRowsetResult As System.Data.DataTable)
        Me.OpenRowsetResult = OpenRowsetResult
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Public Interface IMyCallsChannel
    Inherits IMyCalls, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Partial Public Class MyCallsClient
    Inherits System.ServiceModel.ClientBase(Of IMyCalls)
    Implements IMyCalls

    Public Sub New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    Private Function IMyCalls_MyEcho(ByVal request As MyEchoRequest) As MyEchoResponse Implements IMyCalls.MyEcho
        Return MyBase.Channel.MyEcho(request)
    End Function

    Public Function MyEcho(ByVal strInput As String) As String
        Dim inValue As MyEchoRequest = New MyEchoRequest()
        inValue.strInput = strInput
        Dim retVal As MyEchoResponse = (CType(Me, IMyCalls)).MyEcho(inValue)
        Return retVal.MyEchoResult
    End Function

    Private Function IMyCalls_OpenRowset(ByVal request As OpenRowsetRequest) As OpenRowsetResponse Implements IMyCalls.OpenRowset
        Return MyBase.Channel.OpenRowset(request)
    End Function

    Public Function OpenRowset(ByVal strSQL As String) As System.Data.DataTable
        Dim inValue As OpenRowsetRequest = New OpenRowsetRequest()
        inValue.strSQL = strSQL
        Dim retVal As OpenRowsetResponse = (CType(Me, IMyCalls)).OpenRowset(inValue)
        Return retVal.OpenRowsetResult
    End Function
End Class
