all:
	g++ -o client++ -O2 ../../../../include/membuffer.cpp ../../../../include/tablecache.cpp ../../../../include/aclientw.cpp webasynchandler.cpp client_plusplus.cpp -ldl -std=c++11 -lstdc++ -pthread
	strip -s client++

