all:
	g++ -o ss_client -O2 ../../../../include/membuffer.cpp ../../../../include/tablecache.cpp ../../../../include/aclientw.cpp client_plusplus.cpp -ldl -std=c++11 -lstdc++ -pthread
	strip -s ss_client

