'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1318
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace AdoWebAsync


	''' <summary>
	''' ParallelPage class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class ParallelPage

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' txtCmd control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected txtCmd As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' txtQuery control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected txtQuery As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' gvQuery control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected gvQuery As Global.System.Web.UI.WebControls.GridView

		''' <summary>
		''' lblInfo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblInfo As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' idDoMultiTask control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected idDoMultiTask As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' HyperLink1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' hlParallel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected hlParallel As Global.System.Web.UI.WebControls.HyperLink
	End Class
End Namespace
