// SPLoader.h: interface for the CSocketProServerLoader class.
//
//////////////////////////////////////////////////////////////////////

#ifndef ___SOCKETPRO_SERVER_LOADER__H____
#define ___SOCKETPRO_SERVER_LOADER__H____

#include "uscktpro.h"

typedef bool (WINAPI *PInitSocketProServer) (int nParam);
typedef void (WINAPI *PUninitSocketProServer) ();
typedef bool (WINAPI *PStartSocketProServer) (unsigned int uiPort, unsigned int uiMaxBacklog); 
typedef void (WINAPI *PStopSocketProServer) ();
typedef bool (WINAPI *PIsCanceled) ();
typedef void (WINAPI *PSetOnSSLEvent) (POnSSLEvent pOnSSLEvent);
typedef void (WINAPI *PSetOnWinMessage) (POnWinMessage pOnWinMessage);
typedef void (WINAPI *PSetOnAccept) (POnAccept pOnAccept);
typedef void (WINAPI *PSetOnSwitchTo) (POnSwitchTo pOnSwitchTo);
typedef void (WINAPI *PSetOnIsPermitted) (POnIsPermitted pOnIsPermitted);
typedef void (WINAPI *PSetOnClose) (POnClose pOnClose);
typedef void (WINAPI *PSetOnSend) (POnSend pOnSend);
typedef unsigned long (WINAPI *PGetAuthenticationMethod) ();
typedef void (WINAPI *PSetAuthenticationMethod) (unsigned long ulAuthMethod);
typedef void (WINAPI *PSetSharedAM)(bool bShared);
typedef bool (WINAPI *PGetSharedAM)();
typedef unsigned int (WINAPI *PGetListeningSocket)();
typedef unsigned long (WINAPI *PGetSwitchTime)();
typedef void (WINAPI *PSetSwitchTime) (unsigned long ulSwitchTime);
typedef unsigned int (WINAPI *PGetCountOfClients) ();
typedef unsigned int (WINAPI *PGetClient) (unsigned int uiIndex);
typedef HWND (WINAPI *PGetWin) ();
typedef unsigned long (WINAPI *PGetMainThreadID) ();
typedef int (WINAPI *PGetLastSocketError)();
typedef void (WINAPI *PSetDefaultEncryptionMethod) (tagEncryptionMethod EncryptionMethod);
typedef tagEncryptionMethod (WINAPI *PGetDefaultEncryptionMethod) ();
typedef void (WINAPI *PSetDefaultZip) (bool bZip);
typedef bool (WINAPI *PGetDefaultZip) ();
typedef void (WINAPI *PSetMaxThreadIdleTimeBeforeSuicide) (unsigned long ulMaxThreadIdleTimeBeforeSuicide);
typedef unsigned long (WINAPI *PGetMaxThreadIdleTimeBeforeSuicide)();
typedef void (WINAPI *PSetMaxConnectionsPerClient)(unsigned long ulMaxConnectionsPerClient);
typedef unsigned long (WINAPI *PGetMaxConnectionsPerClient) ();
typedef void (WINAPI *PSetTimerElapse)(unsigned long ulTimerElapse);
typedef unsigned long (WINAPI *PGetTimerElapse)(); 
typedef unsigned long (WINAPI *PGetSMInterval)();
typedef void (WINAPI *PSetSMInterval)(unsigned long ulSMInterval); 
typedef void (WINAPI *PSetPingInterval)(unsigned long ulPingInterval);
typedef unsigned long (WINAPI *PGetPingInterval) ();
typedef void (WINAPI *PSetRecycleGlobalMemoryInterval) (unsigned long ulRecycleGlobalMemoryInterval);
typedef unsigned long (WINAPI *PGetRecycleGlobalMemoryInterval) ();
typedef void (WINAPI *PSetCleanPoolInterval) (unsigned long ulCleanPoolInterval);
typedef unsigned long (WINAPI *PGetCleanPoolInterval) ();
typedef void (WINAPI *PSetCertFile)(const wchar_t *strCertFile);	
typedef void (WINAPI *PSetPrivateKeyFile)(const wchar_t *strPrivateKeyFile);
typedef FARPROC (*PGetOpenSSLProcAddress) (const wchar_t *strOpenSSLFuncName);
typedef HINSTANCE (WINAPI *PAddADll)(const wchar_t *strLibFile, int nParam);
typedef bool (WINAPI *PRemoveADll)(const wchar_t *strLibFile);
typedef unsigned long (WINAPI *PGetCountOfLibraries)();
typedef HINSTANCE (WINAPI *PGetADll)(unsigned long ulIndex);
typedef bool (WINAPI *PRemoveADllByHandle)(HINSTANCE hInstance);
typedef bool (WINAPI *PAddSvsContext)(unsigned long ulSvsID, CSvsContext SvsContext);
typedef CSvsContext (WINAPI *PGetSvsContext)(unsigned long ulSvsID);
typedef bool (WINAPI *PRemoveASvsContext)(unsigned long ulSvsID);
typedef bool (WINAPI *PReplaceSvsContext)(unsigned long ulSvsID, CSvsContext SvsContext);
typedef unsigned long (WINAPI *PGetCountOfServices)();
typedef unsigned long (WINAPI *PGetServiceID)(unsigned long ulIndex);
typedef bool (WINAPI *PAddSlowRequest)(unsigned long ulSvsID, unsigned short usRequestID);
typedef bool (WINAPI *PRemoveSlowRequest)(unsigned long ulSvsID, unsigned short usRequestID);
typedef unsigned short (WINAPI *PGetCountOfSlowRequests)(unsigned long ulSvsID);
typedef void (WINAPI *PRemoveAllSlowRequests)(unsigned long ulSvsID);
typedef unsigned short (WINAPI *PGetSlowRequest)(unsigned long ulSvsID, unsigned short usIndex);
typedef void (WINAPI *PSetGroupsNotifiedWhenEntering)(unsigned long ulGroupsNotifiedWhenEntering);
typedef void (WINAPI *PSetGroupsNotifiedWhenExiting)(unsigned long ulGroupsNotifiedWhenExiting);
typedef unsigned long (WINAPI *PGetGroupsNotifiedWhenEntering)();
typedef unsigned long (WINAPI *PGetGroupsNotifiedWhenExiting)();
typedef void (WINAPI *PSetOnChatRequestComing)(POnChatRequestComing pOnChatRequestComing);
typedef void (WINAPI *PSetOnChatRequestCame)(POnChatRequestCame pOnChatRequestCame);
typedef bool (WINAPI *PAddAChatGroup)(unsigned long ulGroupID, const wchar_t *strDescription);
typedef unsigned long (WINAPI *PGetAChatGroup)(unsigned long ulGroupID, wchar_t *strDescription, unsigned long ulChars);
typedef unsigned char (WINAPI *PGetCountOfChatGroups)();
typedef unsigned long (WINAPI *PGetGroupID)(unsigned char bIndex);
typedef unsigned long (WINAPI *PGetCountOfChatters)(unsigned long ulGroupID);
typedef unsigned int (WINAPI *PGetChatterSocket)(unsigned long ulGroupID, unsigned long ulIndex);
typedef unsigned long (WINAPI *PGetJoinedGroup)(unsigned int hSocket);
typedef bool (WINAPI *PSpeakTo)(unsigned int hSocket, const VARIANT *pvtMsg, unsigned int hSocketTarget);
typedef bool (WINAPI *PSpeakToEx)(unsigned int hSocket, const unsigned char *pMessage, unsigned long ulLen, unsigned int hSocketTarget);
typedef bool (WINAPI *PSpeak)(unsigned int hSocket, const VARIANT *pvtMsg, unsigned long ulGroups);
typedef bool (WINAPI *PSpeakEx)(unsigned int hSocket, const unsigned char *pMessage, unsigned long ulLen, unsigned long ulGroups);
typedef bool (WINAPI *PEnter)(unsigned int hSocket, unsigned long ulGroups);
typedef bool (WINAPI *PExit)(unsigned int hSocket);
typedef void* (WINAPI *PGetSSL)(unsigned int hSocket);
typedef unsigned int (WINAPI *PFindClient)(unsigned int hSocket);
typedef bool (WINAPI *PPostClose)(unsigned int hSocket, unsigned short usError);
typedef unsigned long (WINAPI *PRetrieveBuffer)(unsigned int hSocket, unsigned long ulLen, unsigned char* pBuffer, bool bPeek);
typedef unsigned long (WINAPI *PSendReturnData) (unsigned int hSocket, unsigned short usRequestId, unsigned long ulLen, const unsigned char* pBuffer);
typedef bool (WINAPI *PStartBatching)(unsigned int hSocket);
typedef bool (WINAPI *PCommitBatching)(unsigned int hSocket);
typedef bool (WINAPI *PAbortBatching)(unsigned int hSocket);
typedef bool (WINAPI *PIsBatching)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetBytesBatched)(unsigned int hSocket);
typedef bool (WINAPI *PContinueProcessing)(unsigned int hSocket, unsigned short usRequestID);
typedef void (WINAPI *PResetBytesIn)(unsigned int hSocket, unsigned long ulStart, unsigned long *pulHigh);
typedef void (WINAPI *PResetBytesOut)(unsigned int hSocket, unsigned long ulStart, unsigned long *pulHigh);
typedef unsigned long (WINAPI *PGetBytesIn)(unsigned int hSocket, unsigned long *pulHigh);
typedef unsigned long (WINAPI *PGetBytesOut)(unsigned int hSocket, unsigned long *pulHigh);
typedef unsigned long (WINAPI *PGetCurrentRequestLen)(unsigned int hSocket);
typedef unsigned short (WINAPI *PGetCurrentRequestID)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetLastSndTime)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetLastRcvTime)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetSndBufferSize)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetRcvBufferSize)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetSndBytesInQueue)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetRcvBytesInQueue)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetSvsID)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetTotalMemory)(unsigned int hSocket);
typedef unsigned long (WINAPI *PQueryRequestsInQueue)(unsigned int hSocket);
typedef bool (WINAPI *PGetInterfaceAttributes)(unsigned int hSocket, unsigned long *pulMTU, unsigned long *pulMaxSpeed, unsigned long *pulType, unsigned long *pulMask);
typedef void (WINAPI *PShrinkMemory)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetCountOfMySpecificBytes)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetMySpecificBytes)(unsigned int hSocket, unsigned char* pBuffer, unsigned long ulLen);
typedef bool (WINAPI *PSetBlowFish)(unsigned int hSocket, unsigned char bKeyLen, unsigned char *strKey);
typedef bool (WINAPI *PSetEncryptionMethod)(unsigned int hSocket, tagEncryptionMethod EncryptionMethod);
typedef tagEncryptionMethod (WINAPI *PGetEncryptionMethod)(unsigned int hSocket);
typedef bool (WINAPI *PSetZip)(unsigned int hSocket, bool bZip);
typedef bool (WINAPI *PGetZip)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetUID)(unsigned int hSocket, wchar_t *strUID, unsigned long ulCharLen);
typedef unsigned long (WINAPI *PGetPassword)(unsigned int hSocket, wchar_t *strPassword, unsigned long ulCharLen);
typedef unsigned long (WINAPI *PGetTimeOut)(unsigned int hSocket);
typedef bool (WINAPI *PSetTimeOut)(unsigned int hSocket, unsigned long ulTimeOut);
typedef bool (WINAPI *PGetClientInfo)(unsigned int hSocket, CSwitchInfo *pClientInfo);
typedef bool (WINAPI *PGetServerInfo)(unsigned int hSocket, CSwitchInfo *pServerInfo);
typedef bool (WINAPI *PSetServerInfo)(unsigned int hSocket, CSwitchInfo *pServerInfo);
typedef bool (WINAPI *PIsSameEndian)(unsigned int hSocket);
typedef unsigned long (WINAPI *PGetAssociatedThreadID)(unsigned int hSocket);
typedef unsigned int (WINAPI *PGetAssociatedSocket)();
typedef bool (WINAPI *PGetSockAddr)(unsigned int hSocket, unsigned int *pnSockPort, wchar_t *strIPAddrBuffer, unsigned short usChars);
typedef bool (WINAPI *PGetPeerName)(unsigned int hSocket, unsigned int *pnPeerPort, wchar_t *strPeerAddr, unsigned short usChars);
typedef unsigned long (WINAPI *PGetRequestIDsInQueue)(unsigned int hSocket, unsigned short *pusRequestID, unsigned long ulSize);
typedef bool (WINAPI *PGetLocalName)(wchar_t *strLocalName, unsigned short usChars);
typedef void (WINAPI *PRegister)(unsigned int hSocket, unsigned char *pbLock, unsigned char *pbKey);
typedef void (WINAPI *PCleanTrack)(unsigned int hSocket);
typedef void (WINAPI *PUseMSCert)(bool bMachine, bool bRoot, const wchar_t *strCertSubject);
typedef void (WINAPI *PSetPfxFile)(const wchar_t *strPfxFile, const wchar_t *strPassword);
typedef bool (WINAPI *PSetUseWindowMessagePump) (bool bUseWindowMessagePump);
typedef bool (WINAPI *PGetUseWindowMessagePump) ();
typedef bool (WINAPI *PStartIOPump) ();
typedef bool (WINAPI *PPostQuitPump) (unsigned long ulThreadID);
typedef void (WINAPI *PDropCurrentSlowRequest) (unsigned int hSocket);
typedef bool (WINAPI *PIsClosing) (unsigned int hSocket);
typedef bool (WINAPI *PSendUserMessage) (unsigned int hSocket, const wchar_t *strUserID, const VARIANT *pvtMsg);
typedef bool (WINAPI *PSendUserMessageEx)(unsigned int hSocket, const wchar_t *strUserID, const unsigned char *pMessage, unsigned long ulLen);
typedef bool (WINAPI *PSetPassword)(unsigned int hSocket, const wchar_t *strPassword);
typedef void (WINAPI *PSetZipLevel)(unsigned int hSocket, tagZipLevel zl);
typedef tagZipLevel (WINAPI *PGetZipLevel)(unsigned int hSocket);
typedef bool (WINAPI *PSetHTTPResponseHeader)(unsigned int hSocket, const char *strUTF8Header, const char *strUTF8HeaderValue);
typedef void (WINAPI *PSetHTTPResponseCode)(unsigned int hSocket, unsigned int nHTTPResponseCode);
typedef void (WINAPI *PSetHTTPMaxMessageSize) (unsigned int hSocket, unsigned int nNewMax);
typedef unsigned int (WINAPI *PGetHTTPMaxMessageSize)(unsigned int hSocket);
typedef void (WINAPI *PSetHTTPAutoPartition)(unsigned int hSocket, bool bAutoPartition);
typedef bool (WINAPI *PGetHTTPAutoPartition)(unsigned int hSocket);

typedef void (WINAPI *PSetHTTPServerPush)(bool bEnableHTTPServerPush);
typedef bool (WINAPI *PGetHTTPServerPush)();
typedef bool (WINAPI *PSetUserID) (unsigned int hSocket, const wchar_t *strUserID);
typedef const wchar_t* (WINAPI *PHTTPEnter)(unsigned int hSocket, unsigned long ulGroups, unsigned long dwLeaseTime, const wchar_t *strIpAddr);
typedef bool (WINAPI *PHTTPExit)(unsigned int hSocket, const wchar_t* strPushSessionId);
typedef bool (WINAPI *PHTTPSendUserMessage) (unsigned int hSocket, const wchar_t* strPushSessionId, const wchar_t* strUserID, const VARIANT *pvtMsg);
typedef bool (WINAPI *PHTTPSpeak)(unsigned int hSocket, const wchar_t* strPushSessionId, const VARIANT *pvtMsg, unsigned long ulGroups);
typedef bool (WINAPI *PHTTPSubscribe)(unsigned int hSocket, const wchar_t* strPushSessionId, unsigned long ulTimeout, const wchar_t *strCrossSiteJSCallback);
typedef unsigned long (WINAPI *PGetCountOfHTTPChatters)(unsigned long ulGroupId);
typedef const wchar_t* (WINAPI *PGetHTTPChatId)(unsigned long ulGroupId, unsigned long ulIndex);
typedef bool (WINAPI *PGetHTTPChatContext)(const wchar_t *strChatId, wchar_t **pstrUserID, wchar_t **pstrIpAddr, unsigned long *pLeaseTime, VARIANT *pvtGroups, unsigned long *pTimeout, unsigned long *pCountOfMessages);
typedef void (WINAPI *PSetReturnRandom)(unsigned long ulSvsId, bool bRandom);
typedef bool (WINAPI *PGetReturnRandom)(unsigned long ulSvsId);
typedef void (WINAPI *PDropRequestResult)(unsigned int hSocket, unsigned short usRequestId);
typedef bool (WINAPI *PXSpeak)(unsigned int hSocket, const VARIANT *pvtMsg, const VARIANT *pvtGroups);
typedef bool (WINAPI *PXSpeakEx)(unsigned int hSocket, const unsigned char *pMessage, unsigned long ulLen, unsigned long ulGroupCount, const unsigned long *pGroups);
typedef bool (WINAPI *PXEnter)(unsigned int hSocket, const VARIANT *pvtGroups);
typedef unsigned long (WINAPI *PXGetCountOfChatGroups)();
typedef unsigned long (WINAPI *PXGetGroupID)(unsigned long ulIndex);
typedef unsigned long (WINAPI *PGetJoinedGroupIds)(unsigned int hSocket, unsigned long *pGroupId, unsigned long ulGroupCount);
typedef bool (WINAPI *PXHTTPSpeak)(unsigned int hSocket, const wchar_t* strPushSessionId, const VARIANT *pvtMsg, const VARIANT *pvtGroups);
typedef const wchar_t* (WINAPI *PXHTTPEnter)(unsigned int hSocket, const VARIANT *pvtGroups, unsigned long dwLeaseTime, const wchar_t *strIpAddr);
typedef const VARIANT* (WINAPI *PGetHTTPJoinedGroups)(unsigned int hSocket, const wchar_t *strChatSession);


struct CSocketProServerLoader  
{
public:
	CSocketProServerLoader()
	{
		::memset(this, 0, sizeof(CSocketProServerLoader));	
		//LoadSocketProServer();
	}

	~CSocketProServerLoader()
	{
		if(IsLoaded())
		{
			UnloadSocketProServer();
		}
	}

public:
	bool LoadSocketProServer()
	{
		if(IsLoaded())
			return true;
		m_hSocketProServer = ::LoadLibraryA("usktpror.dll");
		if(m_hSocketProServer == UNULL_PTR)
			return false;
		InitSocketProServer = (PInitSocketProServer) GetProcAddress(m_hSocketProServer, "InitSocketProServer");
		UninitSocketProServer = (PUninitSocketProServer) GetProcAddress(m_hSocketProServer, "UninitSocketProServer");
		StartSocketProServer = (PStartSocketProServer) GetProcAddress(m_hSocketProServer, "StartSocketProServer");
		StopSocketProServer = (PStopSocketProServer) GetProcAddress(m_hSocketProServer, "StopSocketProServer");
		IsCanceled = (PIsCanceled) GetProcAddress(m_hSocketProServer, "IsCanceled");
		SetOnSSLEvent = (PSetOnSSLEvent) GetProcAddress(m_hSocketProServer, "SetOnSSLEvent");
		SetOnWinMessage = (PSetOnWinMessage) GetProcAddress(m_hSocketProServer, "SetOnWinMessage");
		SetOnAccept = (PSetOnAccept) GetProcAddress(m_hSocketProServer, "SetOnAccept");
		SetOnSwitchTo = (PSetOnSwitchTo) GetProcAddress(m_hSocketProServer, "SetOnSwitchTo");
		SetOnIsPermitted = (PSetOnIsPermitted) GetProcAddress(m_hSocketProServer, "SetOnIsPermitted");
		SetOnClose = (PSetOnClose) GetProcAddress(m_hSocketProServer, "SetOnClose");
		SetOnSend = (PSetOnSend) GetProcAddress(m_hSocketProServer, "SetOnSend");
		GetAuthenticationMethod = (PGetAuthenticationMethod) GetProcAddress(m_hSocketProServer, "GetAuthenticationMethod");
		SetAuthenticationMethod = (PSetAuthenticationMethod) GetProcAddress(m_hSocketProServer, "SetAuthenticationMethod");
		SetSharedAM = (PSetSharedAM) GetProcAddress(m_hSocketProServer, "SetSharedAM");
		GetSharedAM = (PGetSharedAM) GetProcAddress(m_hSocketProServer, "GetSharedAM");
		GetListeningSocket = (PGetListeningSocket) GetProcAddress(m_hSocketProServer, "GetListeningSocket");
		GetSwitchTime = (PGetSwitchTime) GetProcAddress(m_hSocketProServer, "GetSwitchTime");
		SetSwitchTime = (PSetSwitchTime) GetProcAddress(m_hSocketProServer, "SetSwitchTime");
		GetCountOfClients = (PGetCountOfClients) GetProcAddress(m_hSocketProServer, "GetCountOfClients");
		GetClient = (PGetClient) GetProcAddress(m_hSocketProServer, "GetClient");
		GetWin = (PGetWin) GetProcAddress(m_hSocketProServer, "GetWin");
		GetMainThreadID = (PGetMainThreadID) GetProcAddress(m_hSocketProServer, "GetMainThreadID");
		GetLastSocketError = (PGetLastSocketError) GetProcAddress(m_hSocketProServer, "GetLastSocketError");
		SetDefaultEncryptionMethod = (PSetDefaultEncryptionMethod) GetProcAddress(m_hSocketProServer, "SetDefaultEncryptionMethod");
		GetDefaultEncryptionMethod = (PGetDefaultEncryptionMethod) GetProcAddress(m_hSocketProServer, "GetDefaultEncryptionMethod");
		SetDefaultZip = (PSetDefaultZip) GetProcAddress(m_hSocketProServer, "SetDefaultZip");
		GetDefaultZip = (PGetDefaultZip) GetProcAddress(m_hSocketProServer, "GetDefaultZip");
		SetMaxThreadIdleTimeBeforeSuicide = (PSetMaxThreadIdleTimeBeforeSuicide) GetProcAddress(m_hSocketProServer, "SetMaxThreadIdleTimeBeforeSuicide");
		GetMaxThreadIdleTimeBeforeSuicide = (PGetMaxThreadIdleTimeBeforeSuicide) GetProcAddress(m_hSocketProServer, "GetMaxThreadIdleTimeBeforeSuicide");
		SetMaxConnectionsPerClient = (PSetMaxConnectionsPerClient) GetProcAddress(m_hSocketProServer, "SetMaxConnectionsPerClient");
		GetMaxConnectionsPerClient = (PGetMaxConnectionsPerClient) GetProcAddress(m_hSocketProServer, "GetMaxConnectionsPerClient");
		SetTimerElapse = (PSetTimerElapse) GetProcAddress(m_hSocketProServer, "SetTimerElapse");
		GetTimerElapse = (PGetTimerElapse) GetProcAddress(m_hSocketProServer, "GetTimerElapse");
		GetSMInterval = (PGetSMInterval) GetProcAddress(m_hSocketProServer, "GetSMInterval");
		SetSMInterval = (PSetSMInterval) GetProcAddress(m_hSocketProServer, "SetSMInterval");
		SetPingInterval = (PSetPingInterval) GetProcAddress(m_hSocketProServer, "SetPingInterval");
		GetPingInterval = (PGetPingInterval) GetProcAddress(m_hSocketProServer, "GetPingInterval");
		SetRecycleGlobalMemoryInterval = (PSetRecycleGlobalMemoryInterval) GetProcAddress(m_hSocketProServer, "SetRecycleGlobalMemoryInterval");
		GetRecycleGlobalMemoryInterval = (PGetRecycleGlobalMemoryInterval) GetProcAddress(m_hSocketProServer, "GetRecycleGlobalMemoryInterval");
		SetCleanPoolInterval = (PSetCleanPoolInterval) GetProcAddress(m_hSocketProServer, "SetCleanPoolInterval");
		GetCleanPoolInterval = (PGetCleanPoolInterval) GetProcAddress(m_hSocketProServer, "GetCleanPoolInterval");
		SetCertFile = (PSetCertFile) GetProcAddress(m_hSocketProServer, "SetCertFile");
		SetPrivateKeyFile = (PSetPrivateKeyFile) GetProcAddress(m_hSocketProServer, "SetPrivateKeyFile");
		GetOpenSSLProcAddress = (PGetOpenSSLProcAddress) GetProcAddress(m_hSocketProServer, "GetOpenSSLProcAddress");
		AddADll = (PAddADll) GetProcAddress(m_hSocketProServer, "AddADll");
		RemoveADll = (PRemoveADll) GetProcAddress(m_hSocketProServer, "RemoveADll");
		GetCountOfLibraries = (PGetCountOfLibraries) GetProcAddress(m_hSocketProServer, "GetCountOfLibraries");
		GetADll = (PGetADll) GetProcAddress(m_hSocketProServer, "GetADll");
		RemoveADllByHandle = (PRemoveADllByHandle) GetProcAddress(m_hSocketProServer, "AddADll");
		AddSvsContext = (PAddSvsContext) GetProcAddress(m_hSocketProServer, "AddSvsContext");
		GetSvsContext = (PGetSvsContext) GetProcAddress(m_hSocketProServer, "GetSvsContext");
		RemoveASvsContext = (PRemoveASvsContext) GetProcAddress(m_hSocketProServer, "RemoveASvsContext");
		ReplaceSvsContext = (PReplaceSvsContext) GetProcAddress(m_hSocketProServer, "ReplaceSvsContext");
		GetCountOfServices = (PGetCountOfServices) GetProcAddress(m_hSocketProServer, "GetCountOfServices");
		GetServiceID = (PGetServiceID) GetProcAddress(m_hSocketProServer, "GetServiceID");
		AddSlowRequest = (PAddSlowRequest) GetProcAddress(m_hSocketProServer, "AddSlowRequest");
		RemoveSlowRequest = (PRemoveSlowRequest) GetProcAddress(m_hSocketProServer, "RemoveSlowRequest");
		GetCountOfSlowRequests = (PGetCountOfSlowRequests) GetProcAddress(m_hSocketProServer, "GetCountOfSlowRequests");
		RemoveAllSlowRequests = (PRemoveAllSlowRequests) GetProcAddress(m_hSocketProServer, "RemoveAllSlowRequests");
		GetSlowRequest = (PGetSlowRequest) GetProcAddress(m_hSocketProServer, "GetSlowRequest");
		SetGroupsNotifiedWhenEntering = (PSetGroupsNotifiedWhenEntering) GetProcAddress(m_hSocketProServer, "SetGroupsNotifiedWhenEntering");
		SetGroupsNotifiedWhenExiting = (PSetGroupsNotifiedWhenExiting) GetProcAddress(m_hSocketProServer, "SetGroupsNotifiedWhenExiting");
		GetGroupsNotifiedWhenEntering = (PGetGroupsNotifiedWhenEntering) GetProcAddress(m_hSocketProServer, "GetGroupsNotifiedWhenEntering");
		GetGroupsNotifiedWhenExiting = (PGetGroupsNotifiedWhenExiting) GetProcAddress(m_hSocketProServer, "GetGroupsNotifiedWhenExiting");
		SetOnChatRequestComing = (PSetOnChatRequestComing) GetProcAddress(m_hSocketProServer, "SetOnChatRequestComing");
		SetOnChatRequestCame = (PSetOnChatRequestCame) GetProcAddress(m_hSocketProServer, "SetOnChatRequestCame");
		AddAChatGroup = (PAddAChatGroup) GetProcAddress(m_hSocketProServer, "AddAChatGroup");
		GetAChatGroup = (PGetAChatGroup) GetProcAddress(m_hSocketProServer, "GetAChatGroup");
		GetCountOfChatGroups = (PGetCountOfChatGroups) GetProcAddress(m_hSocketProServer, "GetCountOfChatGroups");
		GetGroupID = (PGetGroupID) GetProcAddress(m_hSocketProServer, "GetGroupID");
		GetCountOfChatters = (PGetCountOfChatters) GetProcAddress(m_hSocketProServer, "GetCountOfChatters");
		GetChatterSocket = (PGetChatterSocket) GetProcAddress(m_hSocketProServer, "GetChatterSocket");
		GetJoinedGroup = (PGetJoinedGroup) GetProcAddress(m_hSocketProServer, "GetJoinedGroup");
		SpeakTo = (PSpeakTo) GetProcAddress(m_hSocketProServer, "SpeakTo");
		SpeakToEx = (PSpeakToEx) GetProcAddress(m_hSocketProServer, "SpeakToEx");
		Speak = (PSpeak) GetProcAddress(m_hSocketProServer, "Speak");
		SpeakEx = (PSpeakEx) GetProcAddress(m_hSocketProServer, "SpeakEx");
		Enter = (PEnter) GetProcAddress(m_hSocketProServer, "Enter");
		Exit = (PExit) GetProcAddress(m_hSocketProServer, "Exit");
		GetSSL = (PGetSSL) GetProcAddress(m_hSocketProServer, "GetSSL");
		FindClient = (PFindClient) GetProcAddress(m_hSocketProServer, "FindClient");
		PostClose = (PPostClose) GetProcAddress(m_hSocketProServer, "PostClose");
		RetrieveBuffer = (PRetrieveBuffer) GetProcAddress(m_hSocketProServer, "RetrieveBuffer");
		SendReturnData = (PSendReturnData) GetProcAddress(m_hSocketProServer, "SendReturnData");
		StartBatching = (PStartBatching) GetProcAddress(m_hSocketProServer, "StartBatching");
		CommitBatching = (PCommitBatching) GetProcAddress(m_hSocketProServer, "CommitBatching");
		AbortBatching = (PAbortBatching) GetProcAddress(m_hSocketProServer, "AbortBatching");
		IsBatching = (PIsBatching) GetProcAddress(m_hSocketProServer, "IsBatching");
		GetBytesBatched = (PGetBytesBatched) GetProcAddress(m_hSocketProServer, "GetBytesBatched");
		ContinueProcessing = (PContinueProcessing) GetProcAddress(m_hSocketProServer, "ContinueProcessing");
		ResetBytesIn = (PResetBytesIn) GetProcAddress(m_hSocketProServer, "ResetBytesIn");
		ResetBytesOut = (PResetBytesOut) GetProcAddress(m_hSocketProServer, "ResetBytesOut");
		GetBytesIn = (PGetBytesIn) GetProcAddress(m_hSocketProServer, "GetBytesIn");
		GetBytesOut = (PGetBytesOut) GetProcAddress(m_hSocketProServer, "GetBytesOut");
		GetCurrentRequestLen = (PGetCurrentRequestLen) GetProcAddress(m_hSocketProServer, "GetCurrentRequestLen");
		GetCurrentRequestID = (PGetCurrentRequestID) GetProcAddress(m_hSocketProServer, "GetCurrentRequestID");
		GetLastSndTime = (PGetLastSndTime) GetProcAddress(m_hSocketProServer, "GetLastSndTime");
		GetLastRcvTime = (PGetLastRcvTime) GetProcAddress(m_hSocketProServer, "GetLastRcvTime");
		GetSndBufferSize = (PGetSndBufferSize) GetProcAddress(m_hSocketProServer, "GetSndBufferSize");
		GetRcvBufferSize = (PGetRcvBufferSize) GetProcAddress(m_hSocketProServer, "GetRcvBufferSize");
		GetSndBytesInQueue = (PGetSndBytesInQueue) GetProcAddress(m_hSocketProServer, "GetSndBytesInQueue");
		GetRcvBytesInQueue = (PGetRcvBytesInQueue) GetProcAddress(m_hSocketProServer, "GetRcvBytesInQueue");
		GetSvsID = (PGetSvsID) GetProcAddress(m_hSocketProServer, "GetSvsID");
		GetTotalMemory = (PGetTotalMemory) GetProcAddress(m_hSocketProServer, "GetTotalMemory");
		QueryRequestsInQueue = (PQueryRequestsInQueue) GetProcAddress(m_hSocketProServer, "QueryRequestsInQueue");
		GetInterfaceAttributes = (PGetInterfaceAttributes) GetProcAddress(m_hSocketProServer, "GetInterfaceAttributes");
		ShrinkMemory = (PShrinkMemory) GetProcAddress(m_hSocketProServer, "ShrinkMemory");
		GetCountOfMySpecificBytes = (PGetCountOfMySpecificBytes) GetProcAddress(m_hSocketProServer, "GetCountOfMySpecificBytes");
		GetMySpecificBytes = (PGetMySpecificBytes) GetProcAddress(m_hSocketProServer, "GetMySpecificBytes");
		SetBlowFish = (PSetBlowFish) GetProcAddress(m_hSocketProServer, "SetBlowFish");
		SetEncryptionMethod = (PSetEncryptionMethod) GetProcAddress(m_hSocketProServer, "SetEncryptionMethod");
		GetEncryptionMethod = (PGetEncryptionMethod) GetProcAddress(m_hSocketProServer, "GetEncryptionMethod");
		SetZip = (PSetZip) GetProcAddress(m_hSocketProServer, "SetZip");
		GetZip = (PGetZip) GetProcAddress(m_hSocketProServer, "GetZip");
		GetUID = (PGetUID) GetProcAddress(m_hSocketProServer, "GetUID");
		GetPassword = (PGetPassword) GetProcAddress(m_hSocketProServer, "GetPassword");
		GetTimeOut = (PGetTimeOut) GetProcAddress(m_hSocketProServer, "GetTimeOut");
		SetTimeOut = (PSetTimeOut) GetProcAddress(m_hSocketProServer, "SetTimeOut");
		GetClientInfo = (PGetClientInfo) GetProcAddress(m_hSocketProServer, "GetClientInfo");
		GetServerInfo = (PGetServerInfo) GetProcAddress(m_hSocketProServer, "GetServerInfo");
		SetServerInfo = (PSetServerInfo) GetProcAddress(m_hSocketProServer, "SetServerInfo");
		IsSameEndian = (PIsSameEndian) GetProcAddress(m_hSocketProServer, "IsSameEndian");
		GetAssociatedThreadID = (PGetAssociatedThreadID) GetProcAddress(m_hSocketProServer, "GetAssociatedThreadID");
		GetAssociatedSocket = (PGetAssociatedSocket) GetProcAddress(m_hSocketProServer, "GetAssociatedSocket");
		GetSockAddr = (PGetSockAddr) GetProcAddress(m_hSocketProServer, "GetSockAddr");
		GetPeerName = (PGetPeerName) GetProcAddress(m_hSocketProServer, "GetPeerName");
		GetRequestIDsInQueue = (PGetRequestIDsInQueue) GetProcAddress(m_hSocketProServer, "GetRequestIDsInQueue");
		GetLocalName = (PGetLocalName) GetProcAddress(m_hSocketProServer, "GetLocalName");
		Register = (PRegister) GetProcAddress(m_hSocketProServer, "Register");
		CleanTrack = (PCleanTrack) GetProcAddress(m_hSocketProServer, "CleanTrack");
		UseMSCert = (PUseMSCert) GetProcAddress(m_hSocketProServer, "UseMSCert");
		SetPfxFile = (PSetPfxFile) GetProcAddress(m_hSocketProServer, "SetPfxFile");
		SetUseWindowMessagePump = (PSetUseWindowMessagePump) GetProcAddress(m_hSocketProServer, "SetUseWindowMessagePump");
		GetUseWindowMessagePump = (PGetUseWindowMessagePump) GetProcAddress(m_hSocketProServer, "GetUseWindowMessagePump");
		StartIOPump = (PStartIOPump)GetProcAddress(m_hSocketProServer, "StartIOPump");
		PostQuitPump = (PPostQuitPump)GetProcAddress(m_hSocketProServer, "PostQuitPump");
		DropCurrentSlowRequest = (PDropCurrentSlowRequest)GetProcAddress(m_hSocketProServer, "DropCurrentSlowRequest");
		IsClosing =(PIsClosing)GetProcAddress(m_hSocketProServer, "IsClosing");
		SendUserMessage = (PSendUserMessage)GetProcAddress(m_hSocketProServer, "SendUserMessage");
		SendUserMessageEx = (PSendUserMessageEx)GetProcAddress(m_hSocketProServer, "SendUserMessageEx");
		SetPassword = (PSetPassword)GetProcAddress(m_hSocketProServer, "SetPassword");
		SetZipLevel = (PSetZipLevel)GetProcAddress(m_hSocketProServer, "SetZipLevel");
		GetZipLevel = (PGetZipLevel)GetProcAddress(m_hSocketProServer, "GetZipLevel");	
		SetHTTPResponseHeader = (PSetHTTPResponseHeader)GetProcAddress(m_hSocketProServer, "SetHTTPResponseHeader");
		SetHTTPResponseCode = (PSetHTTPResponseCode)GetProcAddress(m_hSocketProServer, "SetHTTPResponseCode");
		SetHTTPMaxMessageSize = (PSetHTTPMaxMessageSize)GetProcAddress(m_hSocketProServer, "SetHTTPMaxMessageSize");
		GetHTTPMaxMessageSize = (PGetHTTPMaxMessageSize)GetProcAddress(m_hSocketProServer, "GetHTTPMaxMessageSize");
		SetHTTPAutoPartition = (PSetHTTPAutoPartition)GetProcAddress(m_hSocketProServer, "SetHTTPAutoPartition");
		GetHTTPAutoPartition = (PGetHTTPAutoPartition)GetProcAddress(m_hSocketProServer, "GetHTTPAutoPartition");
		SetHTTPServerPush = (PSetHTTPServerPush)GetProcAddress(m_hSocketProServer, "SetHTTPServerPush");
		GetHTTPServerPush = (PGetHTTPServerPush)GetProcAddress(m_hSocketProServer, "GetHTTPServerPush");
		SetUserID = (PSetUserID)GetProcAddress(m_hSocketProServer, "SetUserID");
		HTTPEnter = (PHTTPEnter)GetProcAddress(m_hSocketProServer, "HTTPEnter");
		HTTPExit = (PHTTPExit)GetProcAddress(m_hSocketProServer, "HTTPExit");
		HTTPSendUserMessage = (PHTTPSendUserMessage)GetProcAddress(m_hSocketProServer, "HTTPSendUserMessage");
		HTTPSpeak = (PHTTPSpeak)GetProcAddress(m_hSocketProServer, "HTTPSpeak");
		HTTPSubscribe = (PHTTPSubscribe)GetProcAddress(m_hSocketProServer, "HTTPSubscribe");
		GetCountOfHTTPChatters = (PGetCountOfHTTPChatters)GetProcAddress(m_hSocketProServer, "GetCountOfHTTPChatters");
		GetHTTPChatId = (PGetHTTPChatId)GetProcAddress(m_hSocketProServer, "GetHTTPChatId");
		GetHTTPChatContext = (PGetHTTPChatContext)GetProcAddress(m_hSocketProServer, "GetHTTPChatContext");
		SetReturnRandom = (PSetReturnRandom)GetProcAddress(m_hSocketProServer, "SetReturnRandom");
		GetReturnRandom = (PGetReturnRandom)GetProcAddress(m_hSocketProServer, "GetReturnRandom");
		DropRequestResult = (PDropRequestResult)GetProcAddress(m_hSocketProServer, "DropRequestResult");
		XEnter = (PXEnter)GetProcAddress(m_hSocketProServer, "XEnter");
		XSpeak = (PXSpeak)GetProcAddress(m_hSocketProServer, "XSpeak");
		XSpeakEx = (PXSpeakEx)GetProcAddress(m_hSocketProServer, "XSpeakEx");
		XGetCountOfChatGroups = (PXGetCountOfChatGroups)GetProcAddress(m_hSocketProServer, "XGetCountOfChatGroups");
		XGetGroupID = (PXGetGroupID)GetProcAddress(m_hSocketProServer, "XGetGroupID");
		GetJoinedGroupIds = (PGetJoinedGroupIds)GetProcAddress(m_hSocketProServer, "GetJoinedGroupIds");
		XHTTPSpeak = (PXHTTPSpeak)GetProcAddress(m_hSocketProServer, "XHTTPSpeak");
		XHTTPEnter = (PXHTTPEnter)GetProcAddress(m_hSocketProServer, "XHTTPEnter");
		GetHTTPJoinedGroups = (PGetHTTPJoinedGroups)GetProcAddress(m_hSocketProServer, "GetHTTPJoinedGroups");
		
		return true;
	}

	void UnloadSocketProServer()
	{
		if(m_hSocketProServer != UNULL_PTR)
		{
			::FreeLibrary(m_hSocketProServer);
			::memset(this, 0, sizeof(CSocketProServerLoader));
		}
	}

	inline bool IsLoaded()
	{
		return (m_hSocketProServer != UNULL_PTR);
	}

public:
	PInitSocketProServer				InitSocketProServer;
	PUninitSocketProServer				UninitSocketProServer;
	PStartSocketProServer				StartSocketProServer; 
	PStopSocketProServer				StopSocketProServer;
	PIsCanceled							IsCanceled;
	PSetOnSSLEvent						SetOnSSLEvent;
	PSetOnWinMessage					SetOnWinMessage;
	PSetOnAccept						SetOnAccept;
	PSetOnSwitchTo						SetOnSwitchTo;
	PSetOnIsPermitted					SetOnIsPermitted;
	PSetOnClose							SetOnClose;
	PSetOnSend							SetOnSend;
	PGetAuthenticationMethod			GetAuthenticationMethod;
	PSetAuthenticationMethod			SetAuthenticationMethod;
	PSetSharedAM						SetSharedAM;
	PGetSharedAM						GetSharedAM;
	PGetListeningSocket					GetListeningSocket;
	PGetSwitchTime						GetSwitchTime;
	PSetSwitchTime						SetSwitchTime;
	PGetCountOfClients					GetCountOfClients;
	PGetClient							GetClient;
	PGetWin								GetWin;
	PGetMainThreadID					GetMainThreadID;
	PGetLastSocketError					GetLastSocketError;
	PSetDefaultEncryptionMethod			SetDefaultEncryptionMethod;
	PGetDefaultEncryptionMethod			GetDefaultEncryptionMethod;
	PSetDefaultZip						SetDefaultZip;
	PGetDefaultZip						GetDefaultZip;
	PSetMaxThreadIdleTimeBeforeSuicide	SetMaxThreadIdleTimeBeforeSuicide;
	PGetMaxThreadIdleTimeBeforeSuicide	GetMaxThreadIdleTimeBeforeSuicide;
	PSetMaxConnectionsPerClient			SetMaxConnectionsPerClient;
	PGetMaxConnectionsPerClient			GetMaxConnectionsPerClient;
	PSetTimerElapse						SetTimerElapse;
	PGetTimerElapse						GetTimerElapse; 
	PGetSMInterval						GetSMInterval;
	PSetSMInterval						SetSMInterval; 
	PSetPingInterval					SetPingInterval;
	PGetPingInterval					GetPingInterval;
	PSetRecycleGlobalMemoryInterval		SetRecycleGlobalMemoryInterval;
	PGetRecycleGlobalMemoryInterval		GetRecycleGlobalMemoryInterval;
	PSetCleanPoolInterval				SetCleanPoolInterval;
	PGetCleanPoolInterval				GetCleanPoolInterval;
	PSetCertFile						SetCertFile;	
	PSetPrivateKeyFile					SetPrivateKeyFile;
	PGetOpenSSLProcAddress				GetOpenSSLProcAddress;
	PAddADll							AddADll;
	PRemoveADll							RemoveADll;
	PGetCountOfLibraries				GetCountOfLibraries;
	PGetADll							GetADll;
	PRemoveADllByHandle					RemoveADllByHandle;
	PAddSvsContext						AddSvsContext;
	PGetSvsContext						GetSvsContext;
	PRemoveASvsContext					RemoveASvsContext;
	PReplaceSvsContext					ReplaceSvsContext;
	PGetCountOfServices					GetCountOfServices;
	PGetServiceID						GetServiceID;
	PAddSlowRequest						AddSlowRequest;
	PRemoveSlowRequest					RemoveSlowRequest;
	PGetCountOfSlowRequests				GetCountOfSlowRequests;
	PRemoveAllSlowRequests				RemoveAllSlowRequests;
	PGetSlowRequest						GetSlowRequest;
	PSetGroupsNotifiedWhenEntering		SetGroupsNotifiedWhenEntering;
	PSetGroupsNotifiedWhenExiting		SetGroupsNotifiedWhenExiting;
	PGetGroupsNotifiedWhenEntering		GetGroupsNotifiedWhenEntering;
	PGetGroupsNotifiedWhenExiting		GetGroupsNotifiedWhenExiting;
	PSetOnChatRequestComing				SetOnChatRequestComing;
	PSetOnChatRequestCame				SetOnChatRequestCame;
	PAddAChatGroup						AddAChatGroup;
	PGetAChatGroup						GetAChatGroup;
	PGetCountOfChatGroups				GetCountOfChatGroups;
	PGetGroupID							GetGroupID;
	PGetCountOfChatters					GetCountOfChatters;
	PGetChatterSocket					GetChatterSocket;
	PGetJoinedGroup						GetJoinedGroup;
	PSpeakTo							SpeakTo;		
	PSpeakToEx							SpeakToEx;
	PSpeak								Speak;
	PSpeakEx							SpeakEx;
	PEnter								Enter;
	PExit								Exit;
	PGetSSL								GetSSL;
	PFindClient							FindClient;
	PPostClose							PostClose;
	PRetrieveBuffer						RetrieveBuffer;
	PSendReturnData						SendReturnData;
	PStartBatching						StartBatching;
	PCommitBatching						CommitBatching;
	PAbortBatching						AbortBatching;
	PIsBatching							IsBatching;
	PGetBytesBatched					GetBytesBatched;
	PContinueProcessing					ContinueProcessing;
	PResetBytesIn						ResetBytesIn;
	PResetBytesOut						ResetBytesOut;
	PGetBytesIn							GetBytesIn;
	PGetBytesOut						GetBytesOut;
	PGetCurrentRequestLen				GetCurrentRequestLen;
	PGetCurrentRequestID				GetCurrentRequestID;
	PGetLastSndTime						GetLastSndTime;
	PGetLastRcvTime						GetLastRcvTime;
	PGetSndBufferSize					GetSndBufferSize;
	PGetRcvBufferSize					GetRcvBufferSize;
	PGetSndBytesInQueue					GetSndBytesInQueue;
	PGetRcvBytesInQueue					GetRcvBytesInQueue;
	PGetSvsID							GetSvsID;
	PGetTotalMemory						GetTotalMemory;
	PQueryRequestsInQueue				QueryRequestsInQueue;
	PGetInterfaceAttributes				GetInterfaceAttributes;
	PShrinkMemory						ShrinkMemory;
	PGetCountOfMySpecificBytes			GetCountOfMySpecificBytes;
	PGetMySpecificBytes					GetMySpecificBytes;
	PSetBlowFish						SetBlowFish;
	PSetEncryptionMethod				SetEncryptionMethod;
	PGetEncryptionMethod				GetEncryptionMethod;
	PSetZip								SetZip;
	PGetZip								GetZip;
	PGetUID								GetUID;
	PGetPassword						GetPassword;
	PGetTimeOut							GetTimeOut;
	PSetTimeOut							SetTimeOut;
	PGetClientInfo						GetClientInfo;
	PGetServerInfo						GetServerInfo;
	PSetServerInfo						SetServerInfo;
	PIsSameEndian						IsSameEndian;
	PGetAssociatedThreadID				GetAssociatedThreadID;
	PGetAssociatedSocket				GetAssociatedSocket;
	PGetSockAddr						GetSockAddr;
	PGetPeerName						GetPeerName;
	PGetRequestIDsInQueue				GetRequestIDsInQueue;
	PGetLocalName						GetLocalName;
	PRegister							Register;
	PCleanTrack							CleanTrack;
	PUseMSCert							UseMSCert;
	PSetPfxFile							SetPfxFile;
	PSetUseWindowMessagePump			SetUseWindowMessagePump;
	PGetUseWindowMessagePump			GetUseWindowMessagePump;
	PStartIOPump						StartIOPump;
	PPostQuitPump						PostQuitPump;
	PDropCurrentSlowRequest				DropCurrentSlowRequest;
	PIsClosing							IsClosing;
	PSendUserMessage					SendUserMessage;
	PSendUserMessageEx					SendUserMessageEx;
	PSetPassword						SetPassword;
	PSetZipLevel						SetZipLevel;
	PGetZipLevel						GetZipLevel;
	PSetHTTPResponseHeader				SetHTTPResponseHeader;
	PSetHTTPResponseCode				SetHTTPResponseCode;
	PSetHTTPMaxMessageSize				SetHTTPMaxMessageSize;
	PGetHTTPMaxMessageSize				GetHTTPMaxMessageSize;
	PSetHTTPAutoPartition				SetHTTPAutoPartition;
	PGetHTTPAutoPartition				GetHTTPAutoPartition;
	PSetHTTPServerPush					SetHTTPServerPush;
	PGetHTTPServerPush					GetHTTPServerPush;
	PSetUserID							SetUserID;
	PHTTPEnter							HTTPEnter;
	PHTTPExit							HTTPExit;
	PHTTPSendUserMessage				HTTPSendUserMessage;
	PHTTPSpeak							HTTPSpeak;
	PHTTPSubscribe						HTTPSubscribe;
	PGetCountOfHTTPChatters				GetCountOfHTTPChatters;
	PGetHTTPChatId						GetHTTPChatId;
	PGetHTTPChatContext					GetHTTPChatContext;
	PSetReturnRandom					SetReturnRandom;
	PGetReturnRandom					GetReturnRandom;
	PDropRequestResult					DropRequestResult;
	PXSpeak								XSpeak;
	PXEnter								XEnter;
	PXSpeakEx							XSpeakEx;
	PXGetCountOfChatGroups				XGetCountOfChatGroups;
	PXGetGroupID						XGetGroupID;
	PGetJoinedGroupIds					GetJoinedGroupIds;
	PXHTTPSpeak							XHTTPSpeak;
	PXHTTPEnter							XHTTPEnter;
	PGetHTTPJoinedGroups				GetHTTPJoinedGroups;

private:
	HMODULE								m_hSocketProServer;
};

#endif // !defined(AFX_SPLOADER_H__F73E5936_7CC5_4AAC_B7C7_21F4D81B5EC2__INCLUDED_)
