CREATE FUNCTION IsConnected()
RETURNS INTEGER
LANGUAGE C
PARAMETER STYLE SQL
FENCED
NOT DETERMINISTIC
NO EXTERNAL ACTION
ALLOW PARALLEL
EXTERNAL NAME 'SpDB2Push!IsConnected'


CREATE FUNCTION Disconnect()
RETURNS INTEGER
LANGUAGE C
PARAMETER STYLE SQL
FENCED
NOT DETERMINISTIC
NO EXTERNAL ACTION
ALLOW PARALLEL
EXTERNAL NAME 'SpDB2Push!Disconnect'


CREATE FUNCTION Connect(varchar(2048))
RETURNS INTEGER
LANGUAGE C
PARAMETER STYLE SQL
FENCED
NOT DETERMINISTIC
NO EXTERNAL ACTION
ALLOW PARALLEL
EXTERNAL NAME 'SpDB2Push!Connect'


CREATE FUNCTION Notify(varchar(2048), varchar(255))
RETURNS INTEGER
LANGUAGE C
PARAMETER STYLE SQL
FENCED
NOT DETERMINISTIC
NO EXTERNAL ACTION
ALLOW PARALLEL
EXTERNAL NAME 'SpDB2Push!Notify'


CREATE FUNCTION SendUserMessage(varchar(2048), varchar(2048))
RETURNS INTEGER
LANGUAGE C
PARAMETER STYLE SQL
FENCED
NOT DETERMINISTIC
NO EXTERNAL ACTION
ALLOW PARALLEL
EXTERNAL NAME 'SpDB2Push!SendUserMessage'


select Connect('host=cye;port=20901;uid=socketpro;pwd=PassOne') as Res from sysibm.sysdummy1;

select IsConnected() as Res from sysibm.sysdummy1;

select Notify('A DB2 Message', '1:2:3') as Res from sysibm.sysdummy1;

select SendUserMessage('DB2 Message to a User', 'AnyOne') as Res from sysibm.sysdummy1;

select Disconnect() as Res from sysibm.sysdummy1;