//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyCalls")]
public interface IMyCalls
{
    
    // CODEGEN: Parameter 'MyEchoResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCalls/MyEcho", ReplyAction="http://tempuri.org/IMyCalls/MyEchoResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    MyEchoResponse MyEcho(MyEchoRequest request);
    
    // CODEGEN: Parameter 'OpenRowsetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCalls/OpenRowset", ReplyAction="http://tempuri.org/IMyCalls/OpenRowsetResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    OpenRowsetResponse OpenRowset(OpenRowsetRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="MyEcho", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class MyEchoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string strInput;
    
    public MyEchoRequest()
    {
    }
    
    public MyEchoRequest(string strInput)
    {
        this.strInput = strInput;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="MyEchoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class MyEchoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MyEchoResult;
    
    public MyEchoResponse()
    {
    }
    
    public MyEchoResponse(string MyEchoResult)
    {
        this.MyEchoResult = MyEchoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="OpenRowset", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class OpenRowsetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string strSQL;
    
    public OpenRowsetRequest()
    {
    }
    
    public OpenRowsetRequest(string strSQL)
    {
        this.strSQL = strSQL;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="OpenRowsetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class OpenRowsetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataTable OpenRowsetResult;
    
    public OpenRowsetResponse()
    {
    }
    
    public OpenRowsetResponse(System.Data.DataTable OpenRowsetResult)
    {
        this.OpenRowsetResult = OpenRowsetResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMyCallsChannel : IMyCalls, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MyCallsClient : System.ServiceModel.ClientBase<IMyCalls>, IMyCalls
{
    
    public MyCallsClient()
    {
    }
    
    public MyCallsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyCallsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyCallsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyCallsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    MyEchoResponse IMyCalls.MyEcho(MyEchoRequest request)
    {
        return base.Channel.MyEcho(request);
    }
    
    public string MyEcho(string strInput)
    {
        MyEchoRequest inValue = new MyEchoRequest();
        inValue.strInput = strInput;
        MyEchoResponse retVal = ((IMyCalls)(this)).MyEcho(inValue);
        return retVal.MyEchoResult;
    }
    
    OpenRowsetResponse IMyCalls.OpenRowset(OpenRowsetRequest request)
    {
        return base.Channel.OpenRowset(request);
    }
    
    public System.Data.DataTable OpenRowset(string strSQL)
    {
        OpenRowsetRequest inValue = new OpenRowsetRequest();
        inValue.strSQL = strSQL;
        OpenRowsetResponse retVal = ((IMyCalls)(this)).OpenRowset(inValue);
        return retVal.OpenRowsetResult;
    }
}
